# Generated by Django 2.2.5 on 2019-12-04 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20191201_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_of_post',
            field=models.DateField(default=datetime.date(2019, 12, 4)),
        ),
    ]
